# Generated by Django 2.2.1 on 2019-08-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormsCustomize', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemDetails',
        ),
    ]
